FROM node:18-alpine AS builder

WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .

# Expose port
EXPOSE 3000

# Start the server
CMD ["node", "index.js"]

FROM nginx:alpine AS production

# Copy nginx configuration
COPY nginx.whatsapp.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Copy the Node.js app from the builder stage
COPY --from=builder /app /app

# Start Nginx
CMD ["nginx", "-g", "daemon off;"] 