name: Deploy to EasyPanel

on:
  push:
    branches: [ main, konipai-v1 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run build
        run: |
          npm run build
          npm run build:server
          
      - name: Deploy to EasyPanel
        uses: easypanel-io/deploy-action@main
        with:
          server: ${{ secrets.EASYPANEL_SERVER }}
          token: ${{ secrets.EASYPANEL_TOKEN }}
          project: crm-one 